services:
 db:
  image: postgres:alpine3.19
  container_name: portalhelpdesk-db
  restart: always
  ports:
   - 5432:5432
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: postgres
  volumes:
   - portalhelpdesk-data:/var/lib/postgresql/data
  networks:
   - inner-link

 api:
  image: portalhelpdesk
  container_name: portalhelpdesk_api
  restart: always
  ports:
   - 80:8080
   - 443:8081
  env_file:
   - ./api.env
  networks:
   - inner-link
  depends_on:
   - db
   

volumes:
 portalhelpdesk-data:

networks:
 inner-link: