services:
 db:
  image: postgres:alpine3.19
  container_name: portalhelpdesk-db
  restart: always
  ports:
   - 5432:5432
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: postgres
  volumes:
   - portalhelpdesk-data:/var/lib/postgresql/data
  networks:
   - inner-link

volumes:
 portalhelpdesk-data:

networks:
 inner-link: